"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Copy, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { formatInventoryOwnershipStatus, formatLineStatus, formatPlatform, formatPlatformReturnAction, formatPlatformReturnInspectionResult } from "@/lib/status-labels";
import { PlatformReturnInspectionDialog } from "./platform-return-inspection-dialog";
import { InventoryStatusBadge, ReturnInspectionBadge, ShipmentReturnStatusBadge } from "./platform-return-status-badge";

type Detail = {
  shipmentLine: { shipmentLineId: string; shipmentBatchId: string; batchNumber: string; platform: string; shipmentLineStatus: string; shippedAt: string | null; receivedAt: string | null; rejectedAt: string | null; rejectReason: string | null; returnCarrier: string | null; returnTrackingNo: string | null; returnReceivedAt: string | null; };
  inventoryItem: { inventoryItemId: string; inventoryCode: string; productName: string; sku: string | null; currentItemStatus: string; ownershipStatus: string; storageLocation: string | null; currentShipmentCycle: { shipmentLineId: string; batchNumber: string; platform: string; shipmentLineStatus: string } | null; };
  inspection: { result: string; storageLocation: string | null; problemReason: string | null; note: string | null; inspectedAt: string | null; createdAt: string | null; updatedAt: string | null; } | null;
  actionLogs: { id: string; action: string; fromResult: string | null; toResult: string | null; note: string | null; metadata: Record<string, string> | null; createdAt: string | null; }[];
  availableActions: string[]; legacyDirectRestock: boolean; isFinal: boolean;
};
function date(value: string | null) { return value ? new Date(value).toLocaleString("zh-CN") : "未填写"; }
function Fact({ label, value }: { label: string; value: React.ReactNode }) { return <div><p className="text-xs text-muted-foreground">{label}</p><div className="mt-1 break-words text-sm">{value}</div></div>; }

export function PlatformReturnDetail({ shipmentLineId }: { shipmentLineId: string }) {
  const [detail, setDetail] = useState<Detail | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [dialogAction, setDialogAction] = useState<"inspectReturn" | "reviseInspection" | "finalizeInspection" | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await fetch(`/api/platform-returns/${shipmentLineId}`); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(response.status === 404 ? "平台退回记录不存在或无权访问。" : body?.message ?? "平台退回详情加载失败。"); setDetail(body); } catch (cause) { setDetail(null); setError(cause instanceof Error ? cause.message : "平台退回详情加载失败。"); } finally { setLoading(false); } }, [shipmentLineId]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  if (loading) return <Skeleton className="h-[42rem]"/>;
  if (error || !detail) return <div className="space-y-4 py-20 text-center"><p className="text-sm text-destructive">{error ?? "平台退回记录不存在或无权访问。"}</p><Button variant="outline" onClick={() => void load()}>重试</Button></div>;
  const actions = detail.availableActions;
  const copyTracking = async () => { if (!detail.shipmentLine.returnTrackingNo) return; try { await navigator.clipboard.writeText(detail.shipmentLine.returnTrackingNo); toast.success("退回物流单号已复制。"); } catch { toast.error("复制失败，请手动复制。" ); } };
  return <div className="space-y-5" data-testid="platform-return-detail"><Link href="/platform-returns" className={buttonVariants({ variant: "ghost", size: "sm" })}><ArrowLeft/>返回平台退回</Link><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm text-muted-foreground">{detail.inventoryItem.inventoryCode}</p><h1 className="text-2xl font-semibold">{detail.inventoryItem.productName}</h1><p className="text-sm text-muted-foreground">SKU / 色号：{detail.inventoryItem.sku ?? "未填写"}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => void load()}><RefreshCw/>刷新</Button>{actions.includes("inspectReturn") ? <Button size="sm" onClick={() => setDialogAction("inspectReturn")}>退回验货</Button> : null}{actions.includes("reviseInspection") ? <Button size="sm" variant="outline" onClick={() => setDialogAction("reviseInspection")}>修改验货</Button> : null}{actions.includes("finalizeInspection") ? <Button size="sm" onClick={() => setDialogAction("finalizeInspection")}>确定最终结论</Button> : null}</div></div>
    {detail.legacyDirectRestock ? <p className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">该商品由旧版流程直接重新入库，当时未登记平台退回验货记录。</p> : null}
    {detail.shipmentLine.shipmentLineStatus === "RETURNING" ? <p className="rounded-lg border bg-muted/30 p-3 text-sm text-muted-foreground">商品仍在平台退回途中，收到退货后才能登记验货结论。</p> : null}
    {detail.isFinal ? <p className="rounded-lg border bg-muted/30 p-3 text-sm text-muted-foreground">验货已完成，最终结论不可通过普通修改变更。</p> : null}
    <div className="grid gap-4 lg:grid-cols-2"><Card className="rounded-lg shadow-none"><CardHeader><CardTitle className="text-base">平台寄送历史事实</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-4"><Fact label="平台" value={formatPlatform(detail.shipmentLine.platform)}/><Fact label="寄送批次" value={<Link className="underline" href={`/shipments/${detail.shipmentLine.shipmentBatchId}`}>{detail.shipmentLine.batchNumber}</Link>}/><Fact label="寄送明细历史状态" value={<ShipmentReturnStatusBadge status={detail.shipmentLine.shipmentLineStatus}/>}/><Fact label="发货时间" value={date(detail.shipmentLine.shippedAt)}/><Fact label="平台收货时间" value={date(detail.shipmentLine.receivedAt)}/><Fact label="拒收 / 退回时间" value={date(detail.shipmentLine.rejectedAt)}/><Fact label="拒收原因" value={detail.shipmentLine.rejectReason ?? "未填写"}/><Fact label="退回物流" value={<span>{detail.shipmentLine.returnCarrier ?? "未填写"} {detail.shipmentLine.returnTrackingNo ?? ""}{detail.shipmentLine.returnTrackingNo ? <button className="ml-2 text-xs underline" type="button" onClick={() => void copyTracking()}><Copy className="mr-1 inline size-3"/>复制</button> : null}</span>}/><Fact label="用户收到时间" value={date(detail.shipmentLine.returnReceivedAt)}/></CardContent></Card><Card className="rounded-lg shadow-none"><CardHeader><CardTitle className="text-base">库存当前事实</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-4"><Fact label="库存编号" value={<Link className="underline" href={`/inventory/${detail.inventoryItem.inventoryItemId}`}>{detail.inventoryItem.inventoryCode}</Link>}/><Fact label="当前库存状态" value={<InventoryStatusBadge status={detail.inventoryItem.currentItemStatus}/>}/><Fact label="资产归属" value={formatInventoryOwnershipStatus(detail.inventoryItem.ownershipStatus)}/><Fact label="当前库位" value={detail.inventoryItem.storageLocation ?? "未填写"}/><Fact label="当前寄送周期" value={detail.inventoryItem.currentShipmentCycle ? `${detail.inventoryItem.currentShipmentCycle.batchNumber} · ${formatLineStatus(detail.inventoryItem.currentShipmentCycle.shipmentLineStatus)}` : "无"}/></CardContent></Card></div>
    <Card className="rounded-lg shadow-none"><CardHeader><CardTitle className="text-base">当前退回验货结论</CardTitle></CardHeader><CardContent>{detail.inspection ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Fact label="验货结论" value={<ReturnInspectionBadge result={detail.inspection.result}/>}/><Fact label="验货库位" value={detail.inspection.storageLocation ?? "未填写"}/><Fact label="问题原因" value={detail.inspection.problemReason ?? "未填写"}/><Fact label="备注" value={detail.inspection.note ?? "未填写"}/><Fact label="验货时间" value={date(detail.inspection.inspectedAt)}/><Fact label="更新时间" value={date(detail.inspection.updatedAt)}/></div> : <p className="text-sm text-muted-foreground">尚未登记平台退回验货。</p>}</CardContent></Card>
    <Card className="rounded-lg shadow-none"><CardHeader><CardTitle className="text-base">操作日志</CardTitle></CardHeader><CardContent className="space-y-3">{detail.actionLogs.length ? detail.actionLogs.map((log) => <div key={log.id} className="border-l pl-3 text-sm"><p>{formatPlatformReturnAction(log.action)} · {date(log.createdAt)}</p><p className="text-xs text-muted-foreground">{log.fromResult ? `${formatPlatformReturnInspectionResult(log.fromResult)} → ` : ""}{log.toResult ? formatPlatformReturnInspectionResult(log.toResult) : ""}{log.note ? ` · ${log.note}` : ""}</p>{log.metadata ? <p className="mt-1 text-xs text-muted-foreground">{Object.entries(log.metadata).map(([key, value]) => `${key === "previousStorageLocation" ? "原库位" : "新库位"}：${value}`).join(" · ")}</p> : null}</div>) : <p className="text-sm text-muted-foreground">暂无操作日志。</p>}</CardContent></Card>
    <PlatformReturnInspectionDialog open={dialogAction !== null} shipmentLineId={shipmentLineId} inspection={detail.inspection} action={dialogAction} onOpenChange={(open) => !open && setDialogAction(null)} onCompleted={load}/>
  </div>;
}
