"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, Edit3, FilePlus2, Loader2, Pencil, RefreshCw, XCircle } from "lucide-react";
import { toast } from "sonner";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { fieldError, marketErrorMessage, marketJson, marketRequest } from "./market-client";
import { dateTime, fromDateTimeLocal, MarketItemBadge, MarketLifecycleBadge, marketLabel, marketPlatforms, marketQuoteTypes, money, toDateTimeLocal } from "./market-display";
import { MarketItemForm } from "./market-item-form";

type Quote = { id: string; platform: string; quoteType: string; amount: string; recordedAt: string; expiresAt: string | null; sourceType: string; sourceReference: string | null; confirmedAt: string | null; invalidatedAt: string | null; invalidationReason: string | null; note: string | null; lifecycleStatus: string; availableActions: { confirm: boolean; invalidate: boolean; correct: boolean } };
type QuoteTypeSummary = { quoteType: string; currentQuote: Quote | null; latestQuote: Quote | null; availabilityReason: string | null };
type Detail = { marketItem: { id: string; displayName: string; normalizedName: string; skuText: string | null; normalizedSku: string | null; versionText: string | null; conditionText: string | null; packageVariant: string | null; accessoryVariant: string | null; defaultTargetProfitAmount: string | null; note: string | null; isActive: boolean; createdAt: string; updatedAt: string; availableActions: { update: boolean; activate: boolean; deactivate: boolean; createQuote: boolean } }; currentQuotesByPlatform: { platform: string; quoteTypes: QuoteTypeSummary[] }[]; availableActions: { update: boolean; activate: boolean; deactivate: boolean; createQuote: boolean } };
type History = { items: Quote[]; page: number; pageSize: number; total: number };

type QuoteDraft = { platform: string; quoteType: string; amount: string; recordedAt: string; expiresAt: string; sourceReference: string; note: string; confirmImmediately: boolean; invalidationReason: string };
const emptyQuote = (): QuoteDraft => ({ platform: "DEWU", quoteType: "EXPECTED_INCOME", amount: "", recordedAt: toDateTimeLocal(new Date().toISOString()), expiresAt: "", sourceReference: "", note: "", confirmImmediately: false, invalidationReason: "" });

export function MarketDetail({ marketItemId }: { marketItemId: string }) {
  const [detail, setDetail] = useState<Detail | null>(null);
  const [history, setHistory] = useState<History | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<{ status?: number; message: string } | null>(null);
  const [historyFilter, setHistoryFilter] = useState({ platform: "", quoteType: "", lifecycleStatus: "", page: 1 });
  const [editOpen, setEditOpen] = useState(false);
  const [quoteMode, setQuoteMode] = useState<{ mode: "create" | "replace"; quote?: Quote } | null>(null);
  const [invalidateQuote, setInvalidateQuote] = useState<Quote | null>(null);
  const [confirmQuote, setConfirmQuote] = useState<Quote | null>(null);
  const [itemAction, setItemAction] = useState<"activate" | "deactivate" | null>(null);
  const [busy, setBusy] = useState<string | null>(null);

  const historyQuery = useMemo(() => { const params = new URLSearchParams({ page: String(historyFilter.page), pageSize: "20" }); if (historyFilter.platform) params.set("platform", historyFilter.platform); if (historyFilter.quoteType) params.set("quoteType", historyFilter.quoteType); if (historyFilter.lifecycleStatus) params.set("lifecycleStatus", historyFilter.lifecycleStatus); return params.toString(); }, [historyFilter]);
  const load = useCallback(async () => {
    setLoading(true); setError(null); setDetail(null); setHistory(null);
    try {
      const [nextDetail, nextHistory] = await Promise.all([marketRequest<Detail>(`/api/market/items/${marketItemId}`), marketRequest<History>(`/api/market/items/${marketItemId}/quotes?${historyQuery}`)]);
      setDetail(nextDetail); setHistory(nextHistory);
    } catch (cause) {
      const typed = cause as { status?: number };
      setError({ status: typed.status, message: marketErrorMessage(cause) });
    } finally { setLoading(false); }
  }, [historyQuery, marketItemId]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const updateHistoryFilter = (key: "platform" | "quoteType" | "lifecycleStatus", value: string) => setHistoryFilter((old) => ({ ...old, [key]: value, page: 1 }));

  async function perform(action: string, task: () => Promise<unknown>, message: string) {
    setBusy(action);
    try { await task(); toast.success(message); await load(); return true; }
    catch (cause) { toast.error(marketErrorMessage(cause)); return false; }
    finally { setBusy(null); }
  }
  if (loading) return <Skeleton className="h-[42rem]"/>;
  if (error) return <Card className="rounded-lg shadow-none"><CardContent className="space-y-3 py-16 text-center"><p className="text-sm text-destructive">{error.status === 404 ? "行情商品不存在或无权访问。" : error.message}</p><Link href="/market" className={buttonVariants({ variant: "outline" })}>返回行情管理</Link></CardContent></Card>;
  if (!detail) return null;
  const item = detail.marketItem;
  return <div className="space-y-5" data-testid="market-detail">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><Link href="/market" className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:underline"><ArrowLeft className="size-4"/>返回行情管理</Link><div className="mt-2 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold">{item.displayName}</h1><MarketItemBadge active={item.isActive}/></div><p className="mt-1 text-sm text-muted-foreground">SKU / 色号：{item.skuText ?? "未填写"}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" disabled={Boolean(busy)} onClick={() => void load()}><RefreshCw className={busy === "reload" ? "animate-spin" : ""}/>刷新</Button>{item.availableActions.update ? <Button variant="outline" size="sm" onClick={() => setEditOpen(true)}><Pencil/>编辑商品</Button> : null}{item.availableActions.createQuote ? <Button size="sm" onClick={() => setQuoteMode({ mode: "create" })}><FilePlus2/>新增手工报价</Button> : null}{item.availableActions.deactivate ? <Button variant="outline" size="sm" disabled={Boolean(busy)} onClick={() => setItemAction("deactivate")}>停用商品</Button> : null}{item.availableActions.activate ? <Button size="sm" disabled={Boolean(busy)} onClick={() => setItemAction("activate")}>重新启用</Button> : null}</div></div>
    <Card className="rounded-lg shadow-none"><CardHeader><CardTitle className="text-base">商品基本信息</CardTitle></CardHeader><CardContent className="grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><Fact label="SKU / 色号" value={item.skuText ?? "未填写"}/><Fact label="标准化名称（服务端）" value={item.normalizedName}/><Fact label="标准化 SKU（服务端）" value={item.normalizedSku ?? "未填写"}/><Fact label="版本" value={item.versionText ?? "未填写"}/><Fact label="成色" value={item.conditionText ?? "未填写"}/><Fact label="包装" value={item.packageVariant ?? "未填写"}/><Fact label="配件" value={item.accessoryVariant ?? "未填写"}/><Fact label="默认目标利润" value={money(item.defaultTargetProfitAmount)}/><Fact label="创建时间" value={dateTime(item.createdAt)}/><Fact label="更新时间" value={dateTime(item.updatedAt)}/><div className="sm:col-span-2 lg:col-span-4"><Fact label="备注" value={item.note ?? "未填写"}/></div></CardContent></Card>
    <section className="space-y-3"><div><h2 className="text-lg font-semibold">当前有效行情</h2><p className="text-sm text-muted-foreground">由服务端共享查询层判定；平台展示价格不等于预计收入，也不代表实际到账。</p></div><div className="grid gap-3 lg:grid-cols-2">{detail.currentQuotesByPlatform.map((platform) => <Card key={platform.platform} className="rounded-lg shadow-none"><CardHeader className="pb-3"><CardTitle className="text-base">{marketLabel(platform.platform)}</CardTitle></CardHeader><CardContent className="space-y-3">{platform.quoteTypes.map((summary) => <CurrentQuote key={summary.quoteType} summary={summary}/>)}</CardContent></Card>)}</div></section>
    <section className="space-y-3"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">历史报价</h2><p className="text-sm text-muted-foreground">历史记录不会被覆盖或删除；替代修正会保留原报价。</p></div>{item.availableActions.createQuote ? <Button variant="outline" size="sm" onClick={() => setQuoteMode({ mode: "create" })}><FilePlus2/>新增报价</Button> : null}</div><Card className="rounded-lg shadow-none"><CardContent className="grid gap-3 p-4 md:grid-cols-4"><select aria-label="历史报价平台" className="h-9 rounded-md border bg-background px-3 text-sm" value={historyFilter.platform} onChange={(event) => updateHistoryFilter("platform", event.target.value)}><option value="">全部平台</option>{marketPlatforms.map((value) => <option key={value} value={value}>{marketLabel(value)}</option>)}</select><select aria-label="历史报价类型" className="h-9 rounded-md border bg-background px-3 text-sm" value={historyFilter.quoteType} onChange={(event) => updateHistoryFilter("quoteType", event.target.value)}><option value="">全部报价类型</option>{marketQuoteTypes.map((value) => <option key={value} value={value}>{marketLabel(value)}</option>)}</select><select aria-label="历史报价状态" className="h-9 rounded-md border bg-background px-3 text-sm" value={historyFilter.lifecycleStatus} onChange={(event) => updateHistoryFilter("lifecycleStatus", event.target.value)}><option value="">全部状态</option><option value="UNCONFIRMED">待确认</option><option value="CURRENT">当前有效</option><option value="SUPERSEDED">已有更新报价</option><option value="EXPIRED">已过期</option><option value="INVALIDATED">已失效</option></select></CardContent></Card>{!history?.items.length ? <Card className="rounded-lg shadow-none"><CardContent className="py-12 text-center text-sm text-muted-foreground">暂无符合条件的历史报价</CardContent></Card> : <div className="space-y-3">{history.items.map((quote) => <QuoteRow key={quote.id} quote={quote} disabled={Boolean(busy)} onConfirm={() => setConfirmQuote(quote)} onInvalidate={() => setInvalidateQuote(quote)} onReplace={() => setQuoteMode({ mode: "replace", quote })}/>)}</div>}<div className="flex items-center justify-between text-sm"><p className="text-muted-foreground">共 {history?.total ?? 0} 条</p><div className="flex gap-2"><Button variant="outline" size="sm" disabled={historyFilter.page <= 1 || Boolean(busy)} onClick={() => setHistoryFilter((old) => ({ ...old, page: old.page - 1 }))}>上一页</Button><Button variant="outline" size="sm" disabled={!history || historyFilter.page * history.pageSize >= history.total || Boolean(busy)} onClick={() => setHistoryFilter((old) => ({ ...old, page: old.page + 1 }))}>下一页</Button></div></div></section>
    <Dialog open={editOpen} onOpenChange={setEditOpen}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>编辑行情商品</DialogTitle><DialogDescription>保存后以服务端返回的标准化结果为准，历史报价不会被改写。</DialogDescription></DialogHeader><MarketItemForm key={`${item.id}-${item.updatedAt}-${editOpen ? "open" : "closed"}`} marketItemId={item.id} initial={item} onSuccess={() => { toast.success("行情商品已更新"); setEditOpen(false); void load(); }}/></DialogContent></Dialog>
    <QuoteFormDialog open={quoteMode !== null} mode={quoteMode?.mode ?? "create"} quote={quoteMode?.quote} marketItemId={item.id} onOpenChange={(open) => !open && setQuoteMode(null)} onSuccess={() => { setQuoteMode(null); void load(); }}/>
    <InvalidateDialog open={invalidateQuote !== null} busy={busy === "invalidate"} onOpenChange={(open) => !open && setInvalidateQuote(null)} onSubmit={async (reason) => { const done = await perform("invalidate", () => marketJson(`/api/market/quotes/${invalidateQuote?.id}/invalidate`, "POST", { reason }), "报价已失效"); if (done) setInvalidateQuote(null); }}/>
    <AlertDialog open={confirmQuote !== null} onOpenChange={(open) => !open && setConfirmQuote(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>确认报价</AlertDialogTitle><AlertDialogDescription>确认后是否成为当前有效行情仍由服务端按记录时间、确认状态和有效期统一判断。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy === "confirm"}>返回</AlertDialogCancel><AlertDialogAction disabled={busy === "confirm"} onClick={(event) => { event.preventDefault(); void (async () => { const done = await perform("confirm", () => marketJson(`/api/market/quotes/${confirmQuote?.id}/confirm`, "POST"), "报价已确认"); if (done) setConfirmQuote(null); })(); }}>{busy === "confirm" ? <Loader2 className="animate-spin"/> : <Check/>}确认报价</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={itemAction !== null} onOpenChange={(open) => !open && setItemAction(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{itemAction === "deactivate" ? "停用行情商品" : "重新启用行情商品"}</AlertDialogTitle><AlertDialogDescription>{itemAction === "deactivate" ? "停用后保留全部历史报价，但不能新建或确认报价。" : "重新启用后可继续录入和确认报价。"}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={Boolean(busy)}>返回</AlertDialogCancel><AlertDialogAction disabled={Boolean(busy)} onClick={(event) => { event.preventDefault(); const action = itemAction; void (async () => { const done = await perform(action!, () => marketJson(`/api/market/items/${item.id}/${action === "deactivate" ? "deactivate" : "reactivate"}`, "POST"), action === "deactivate" ? "行情商品已停用" : "行情商品已重新启用"); if (done) setItemAction(null); })(); }}>{busy ? <Loader2 className="animate-spin"/> : null}确认</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}

function Fact({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 break-words">{value}</p></div>; }
function CurrentQuote({ summary }: { summary: QuoteTypeSummary }) { return <div className="rounded-md border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium text-sm">{marketLabel(summary.quoteType)}</p>{summary.currentQuote ? <MarketLifecycleBadge status={summary.currentQuote.lifecycleStatus}/> : <Badge variant="outline">暂无当前有效行情</Badge>}</div>{summary.currentQuote ? <div className="mt-2 grid gap-1 text-xs text-muted-foreground sm:grid-cols-2"><p className="text-base font-semibold text-foreground">{money(summary.currentQuote.amount)}</p><p>记录时间：{dateTime(summary.currentQuote.recordedAt)}</p><p>到期时间：{dateTime(summary.currentQuote.expiresAt)}</p><p>确认时间：{dateTime(summary.currentQuote.confirmedAt)}</p><p className="sm:col-span-2">来源：{marketLabel(summary.currentQuote.sourceType)}{summary.currentQuote.note ? ` · ${summary.currentQuote.note}` : ""}</p></div> : <p className="mt-2 text-sm text-muted-foreground">{marketLabel(summary.availabilityReason, "暂无有效行情")}</p>}</div>; }
function QuoteRow({ quote, disabled, onConfirm, onInvalidate, onReplace }: { quote: Quote; disabled: boolean; onConfirm: () => void; onInvalidate: () => void; onReplace: () => void }) { return <Card className="rounded-lg shadow-none"><CardContent className="space-y-3 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{marketLabel(quote.platform)} · {marketLabel(quote.quoteType)}</p><MarketLifecycleBadge status={quote.lifecycleStatus}/></div><p className="mt-1 text-xl font-semibold">{money(quote.amount)}</p><p className="mt-1 text-xs text-muted-foreground">手工录入 · 记录于 {dateTime(quote.recordedAt)} · 到期 {dateTime(quote.expiresAt)}</p></div><div className="flex flex-wrap gap-2">{quote.availableActions.confirm ? <Button size="sm" disabled={disabled} onClick={onConfirm}><Check/>确认</Button> : null}{quote.availableActions.invalidate ? <Button variant="outline" size="sm" disabled={disabled} onClick={onInvalidate}><XCircle/>失效</Button> : null}{quote.availableActions.correct ? <Button variant="outline" size="sm" disabled={disabled} onClick={onReplace}><Edit3/>替代修正</Button> : null}</div></div><div className="grid gap-2 text-xs text-muted-foreground sm:grid-cols-3"><p>确认时间：{dateTime(quote.confirmedAt)}</p><p>来源说明：{quote.sourceReference ?? "未填写"}</p><p>备注：{quote.note ?? "未填写"}</p>{quote.invalidatedAt ? <p className="sm:col-span-3">失效时间：{dateTime(quote.invalidatedAt)} · 原因：{quote.invalidationReason ?? "未填写"}</p> : null}</div></CardContent></Card>; }

function QuoteFormDialog({ open, mode, quote, marketItemId, onOpenChange, onSuccess }: { open: boolean; mode: "create" | "replace"; quote?: Quote; marketItemId: string; onOpenChange: (open: boolean) => void; onSuccess: () => void }) {
  const [value, setValue] = useState<QuoteDraft>(emptyQuote); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [errors, setErrors] = useState<Record<string, string[]>>({});
  useEffect(() => { if (open) queueMicrotask(() => { setValue(quote ? { platform: quote.platform, quoteType: quote.quoteType, amount: quote.amount, recordedAt: toDateTimeLocal(quote.recordedAt), expiresAt: toDateTimeLocal(quote.expiresAt), sourceReference: quote.sourceReference ?? "", note: quote.note ?? "", confirmImmediately: quote.confirmedAt !== null, invalidationReason: "" } : emptyQuote()); setError(null); setErrors({}); }); }, [open, quote]);
  function set(key: keyof QuoteDraft, next: string | boolean) { setValue((old) => ({ ...old, [key]: next })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!value.amount.trim() || Number.isNaN(Number(value.amount)) || Number(value.amount) < 0) { setErrors({ amount: ["请输入大于或等于 0 的金额。"] }); return; } if (!value.recordedAt) { setErrors({ recordedAt: ["请选择记录时间。"] }); return; } if (value.expiresAt && new Date(value.expiresAt) <= new Date(value.recordedAt)) { setErrors({ expiresAt: ["有效期必须晚于记录时间。"] }); return; } if (mode === "replace" && !value.invalidationReason.trim()) { setErrors({ invalidationReason: ["请填写替代修正原因。"] }); return; } setSaving(true); setError(null); setErrors({}); const payload = { platform: value.platform, quoteType: value.quoteType, amount: value.amount.trim(), recordedAt: fromDateTimeLocal(value.recordedAt), expiresAt: fromDateTimeLocal(value.expiresAt), sourceReference: value.sourceReference.trim() || null, note: value.note.trim() || null, confirmImmediately: value.confirmImmediately, ...(mode === "replace" ? { invalidationReason: value.invalidationReason.trim() } : {}) }; try { if (mode === "replace") await marketJson(`/api/market/quotes/${quote?.id}/replace`, "POST", payload); else await marketJson(`/api/market/items/${marketItemId}/quotes`, "POST", payload); toast.success(mode === "replace" ? "报价已替代修正" : "手工报价已创建"); onSuccess(); } catch (cause) { setError(marketErrorMessage(cause)); const next: Record<string, string[]> = {}; for (const field of ["amount", "recordedAt", "expiresAt", "invalidationReason", "form"]) { const message = fieldError(cause, field); if (message) next[field] = [message]; } setErrors(next); } finally { setSaving(false); } }
  return <Dialog open={open} onOpenChange={(next) => !saving && onOpenChange(next)}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{mode === "replace" ? "替代修正报价" : "新增手工报价"}</DialogTitle><DialogDescription>{mode === "replace" ? "系统会失效原报价并创建独立的新报价，原记录会保留在历史中。" : "报价默认未确认；是否成为当前有效行情由服务端统一判断。"}</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={submit} noValidate><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1"><Label>平台</Label><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={value.platform} onChange={(event) => set("platform", event.target.value)}>{marketPlatforms.map((platform) => <option key={platform} value={platform}>{marketLabel(platform)}</option>)}</select></div><div className="space-y-1"><Label>报价类型</Label><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={value.quoteType} onChange={(event) => set("quoteType", event.target.value)}>{marketQuoteTypes.map((type) => <option key={type} value={type}>{marketLabel(type)}</option>)}</select></div><Field label="金额" type="text" value={value.amount} onChange={(next) => set("amount", next)} placeholder="例如：300.00" error={errors.amount?.[0]}/><Field label="记录时间" type="datetime-local" value={value.recordedAt} onChange={(next) => set("recordedAt", next)} error={errors.recordedAt?.[0]}/><Field label="有效期" type="datetime-local" value={value.expiresAt} onChange={(next) => set("expiresAt", next)} error={errors.expiresAt?.[0]}/><Field label="来源说明" type="text" value={value.sourceReference} onChange={(next) => set("sourceReference", next)} placeholder="可选"/></div>{mode === "replace" ? <Field label="替代修正原因" type="text" value={value.invalidationReason} onChange={(next) => set("invalidationReason", next)} error={errors.invalidationReason?.[0]}/> : null}<div className="space-y-1"><Label>备注</Label><Textarea value={value.note} onChange={(event) => set("note", event.target.value)} placeholder="可选"/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.confirmImmediately} onChange={(event) => set("confirmImmediately", event.target.checked)}/>创建后立即确认报价</label>{error ? <p className="text-sm text-destructive">{error}</p> : null}<DialogFooter><Button type="button" variant="outline" disabled={saving} onClick={() => onOpenChange(false)}>返回</Button><Button type="submit" disabled={saving}>{saving ? <Loader2 className="animate-spin"/> : null}{mode === "replace" ? "提交替代修正" : "创建报价"}</Button></DialogFooter></form></DialogContent></Dialog>;
}
function Field({ label, type, value, onChange, placeholder, error }: { label: string; type: string; value: string; onChange: (value: string) => void; placeholder?: string; error?: string }) { return <div className="space-y-1"><Label>{label}</Label><Input type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)}/>{error ? <p className="text-xs text-destructive">{error}</p> : null}</div>; }
function InvalidateDialog({ open, busy, onOpenChange, onSubmit }: { open: boolean; busy: boolean; onOpenChange: (open: boolean) => void; onSubmit: (reason: string) => Promise<void> }) { const [reason, setReason] = useState(""); const [error, setError] = useState<string | null>(null); useEffect(() => { if (open) queueMicrotask(() => { setReason(""); setError(null); }); }, [open]); return <Dialog open={open} onOpenChange={(next) => !busy && onOpenChange(next)}><DialogContent><DialogHeader><DialogTitle>失效报价</DialogTitle><DialogDescription>失效后历史报价会保留。服务端会重新选择其他符合条件的当前有效行情。</DialogDescription></DialogHeader><div className="space-y-1"><Label>失效原因</Label><Textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="必填"/>{error ? <p className="text-xs text-destructive">{error}</p> : null}</div><DialogFooter><Button variant="outline" disabled={busy} onClick={() => onOpenChange(false)}>返回</Button><Button variant="destructive" disabled={busy} onClick={() => { if (!reason.trim()) { setError("请填写失效原因。"); return; } void onSubmit(reason.trim()); }}>{busy ? <Loader2 className="animate-spin"/> : <><XCircle/>确认失效</>}</Button></DialogFooter></DialogContent></Dialog>; }
